language: python
python:
  - '3.4'
  - '3.5'

script: python -m unittest

notifications:
  slack:
    secure: qJfSkj9yxPn8ZtAvUBk+9phzr0JHAsNUwmdkWZYZNXztT7JKXj2fCoUbylTM63/YqENJYipJxWsRKESRPqDITAGODPqiy8szxeFseMNpBXhTjlDwvekWU1h2aGEXXdpl+AXkg7XfTL+9oanyQ1Kjg4Iii3AH3vU3DmbKCTCNDVVrykwG/fLNUiKYFMbBbtpCSmxF3pHFJP4/0NAVmctio9EJk23E1jWdEBvo6bnYRTanTB9/yBsspGyhlYgnueRadQXrW35lcnfdFuAVcYPFte6GcZAaZucPhwCHMRT/zkqqeRoRdqQ7oy9PlyV+NialLkEQhbr87PtExy+kGd23i4B3VheJofapMXLsj3Uw1IqZ2nUjZWx6ZEw2aiNKRa5Uyp3J8eS/bqsiHRmrsYpMP2Ysk2x/ovfuxZ3AxV9R0NVQjCaSsDhb03cD7VsRrK71rDMnlE9/cbhKmpfzpgfpS/8bmyFGsIu8rI2Shqy4NiEHMg425QqB/smBTtUJWLPs1ILzMG3A9t4NJ5cyUZhnxYN0iqjNjV1ZzxUBQmq7uvhhXdT8mUhhg8NIUNwkJHeAxmbnnosOjjJyNRmZsBBUHczx71tJUwpAvavFgerYIrxsitQVe4QY77492CimS+5NAu3uIJxywlm2sbVv4fWrgnVHg3iBFLGkptQT1d9eNYI=
